version: "3.8"

services:
  postgresDB:
    image: postgres:14-alpine
    container_name: postgresDB
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - "./db:/var/lib/postgresql/data"

  migration:
    depends_on:
      - postgresDB
    image: liquibase/liquibase:4.17
    container_name: postgres-migration
    restart: on-failure
    volumes:
      - ./liquibase/changeLog/:/liquibase/changelog/
      - ./liquibase/scripts:/liquibase/scripts
    command: update --changelog-file=dbchangelog.xml --url=jdbc:postgresql://postgresDB:5432/postgres --username=user --password=1234